### PR TITLE
All features for First project "Hello Microverse"

### PR DESCRIPTION
**Pull request by enmanuelbayen**
Features added on this branch:

- Add Gitignore file
- Add Css format on req
- Add Html format on req
- Add Readme First features
- Add github/workflows/linters.yml files
- Add node modules
- Add stylelintrc.json
- Add hintrc file
- Add packege.json

### CODE REVIEW

**Review by braincee — CHANGES_REQUESTED** [review]
Hello @enmanuelbayen  ✋, I am @braincee your Code Reviewer

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close

HIGHLIGHTS
------

 - Meaningful title and summary for PR ✅

REQUIRED CHANGES ♻️
------

- [x] Please add a professional README file as it is a project requirement.
- [x] Please I found out that `linters.yml`, `.hintrc`, `.stylelintrc.json` files are empty. Please add the files correctly in order to check for linters. This is a [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to help you with the project requirements.
- [x] Please the `index.html`, `style.css` and `test.md` files are empty. Kindly check this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) for the project requirements


OPTIONAL CHANGES
--------

- [ ] [OPTIONAL] Please do not close or merge a pull request that has been reviewed and not yet approved. Only merge pull requests that have been approved.

**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enmanuelbayen** [comment]
Hello, thanks for your answer! @braincee

I already implemented the necessary changes but I have a question.

I created a new repo where I did everything correctly, will it affect my
review by sending a new repo to the one I initially sent?

**Comment by enmanuelbayen** [comment]
I read that you can't use new repos once you've already sent one for review.

I already updated the branch with everything that was initially missing (the reason was that there was no autosave)

In the other repo that I created, I kept the commits consistent with each change. I don't know if it can be seen after transferring the changes from that repo to this one.

Thanks in advance! @braincee

**Review by ABDULALI3468 — APPROVED** [review]
Hi @enmanuelbayen , 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## My Personal Remarks

I found you to be very enthusiastic and the detailed work that you did was exceptional. Keep shining! 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: GitHub followers
> * This is My **Linkedin**: [Linkedin Badge](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [Twitter Badge](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
